### ISSUE TITLE
UTF escape commands in tokenizer for quoted strings

### ISSUE THREAD

**Issue by clord** [pliosoft/toml-parse#6]
Error from burnt sushi tests:

```
Test: unicode-escape (valid)

Values for key 'answer4' don't match. Expected a value of 'δ' but got '\u03B4'.
```

To fix, tokenizer has to decode escape sequences. I have some code that does this somewhere, just have to find it.
- [ ] determine when to decode sequences (single quoted? double quoted? identifiers?)
- [ ] decode sequences
- [ ] which sequences? `\u`? `\x`? C-style `\r`, `\n`, `\t`, `\0`?

**Comment by pbrisbin** [comment]
This may be valuable: https://github.com/cies/htoml/blob/master/src/Text/Toml/Parser.hs#L258

**Comment by clord** [comment]
Toml's spec specifies the same list:
https://github.com/toml-lang/toml#string
